server:
  port: 8085

spring:
  application:
    name: analytics-service
  kafka:
    bootstrap-servers: kafka:9092
  datasource:
    url: jdbc:postgresql://postgres-analytics:5432/analytics_db
#    url: jdbc:postgresql://localhost:5435/analytics_db
    username: user
    password: password
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  elasticsearch:
    uris: http://elasticsearch:9200
  data:
    redis:
      host: redis
      port: 6379

logging:
  level:
    root: INFO
    com.inventory_system: DEBUG
    org.springframework: INFO
    org.apache.kafka: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n"