server:
  port: 8082

spring:
  application:
    name: product-service
  kafka:
    bootstrap-servers: kafka:9092
  datasource:
    url: jdbc:postgresql://postgres-product:5432/product_db
#    url: jdbc:postgresql://localhost:5433/product_db
    username: user
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  data:
    redis:
      host: redis
      port: 6379

  elasticsearch:
    uris: http://elasticsearch:9200

logging:
  level:
    root: INFO
    com.inventory_system: DEBUG
    org.springframework: INFO
    org.apache.kafka: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n"